version: '3.8'
networks:
  local:
    external: true
    name: local
services:
  service-ui:
    container_name: service-ui
    image: node:20-alpine
    working_dir: /app
    command: npm run dev:ui-fresh
    ports:
      - '8080:8080'
    networks:
      - local
    volumes:
      - ./:/app
    healthcheck:
      test: wget -nv -t1 --spider http://localhost:8080 || exit 1
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 5s
    environment:
      VITE_CJS_IGNORE_WARNING: true
      API_SERVICE_URL: http://service-api:8080
  service-api:
    container_name: service-api
    image: node:20-alpine
    working_dir: /app
    command: npm run dev:api
    depends_on:
      service-ui:
        condition: service_healthy
    networks:
      - local
    volumes:
      - ./:/app
